### PR TITLE
Fix directory issue

### LINKED ISSUE #241: SIS Directory cant be accessed
followings are the issues we encountered.

 (1) A user (Chilaw Zonal Coordinator) requested to fix Grafana log in problem.

(2) Added the e-mail  address of Chilaw zonal coordinator to SIS.

(3) User was not found in SIS, after adding the e-mail address.

User is not in Prod – Master database. But is in Prod- Slave database. (Chilaw)

Puttalam Zonal Coordinator is not found in the system.

Puttalam zonal coordinator is not in both Prod – Master database and Prod- Slave database.

404 Error occurs when trying to access the directory.

### PR DESCRIPTION
**Pull request by mohamednizar**
## Purpose

The purpose of this PR is to fix #241 

## Goals

This will fix the directory access issue, after this  we can create and add user via direcotry.

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

File: plugins/Directory/src/Model/Table/DirectoriesTable.php [hunk 1]
```diff
@@ -146,6 +146,13 @@ public function beforeDelete(Event $event, Entity $entity)
             $this->Alert->error($message, ['type' => 'string', 'reset' => true]);
             return false;
         }
+        $userId = $this->Session->read('Auth.User.id');
+        if($entity->id == $userId){
+            $event->stopPropagation();
+            $message = __('You cannot delete your record by your self');
```
Comment (kosalag) [inline plugins/Directory/src/Model/Table/DirectoriesTable.php:152]: message is confusing a bit. 
something like "You are not allowed to delete your own profile" would be more meaningful

**Review by kosalag — APPROVED** [review]
